# Generated by Django 5.1.2 on 2024-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_profile_teams_profile_team_alter_team_image'),
        ('Projects', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='teams',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(related_name='project_team', to='Accounts.team'),
        ),
    ]
