# Generated by Django 5.1.2 on 2024-11-29 23:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_remove_task_team_alter_task_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admins',
            field=models.ManyToManyField(related_name='task_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
