# Generated by Django 5.1.2 on 2024-11-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_alter_task_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
    ]
