# Generated by Django 5.1.2 on 2024-11-23 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_profile_user_profile_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 21, 20, 57, 82849, tzinfo=datetime.timezone.utc)),
        ),
    ]
