# Generated by Django 5.1.2 on 2024-11-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_projects', to='Projects.task'),
        ),
    ]
