# Generated by Django 5.1.2 on 2024-11-23 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_date_joined_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 21, 31, 55, 918924, tzinfo=datetime.timezone.utc)),
        ),
    ]
