# Generated by Django 5.1.2 on 2024-11-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_profile_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='teams',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_team', to='Accounts.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default='accounts/team/default/defalt_avatar.png', upload_to='accounts/team/'),
        ),
    ]
