# Generated by Django 5.1.2 on 2024-11-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_remove_profile_teams_profile_team_alter_team_image'),
        ('Projects', '0007_subtask_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='profile_team', to='Accounts.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='team_projects', to='Projects.task'),
        ),
    ]
