# Generated by Django 5.1.2 on 2024-11-23 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_profile_date_joined_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 21, 37, 18, 792408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Default_user_<built-in function id>', max_length=150, unique=True),
        ),
    ]
