# Generated by Django 5.1.2 on 2024-12-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
