# Generated by Django 5.1.2 on 2024-11-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_profile_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Default_email_<built-in function id>', max_length=100, unique=True),
        ),
    ]
